//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wzd.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WZDTYPE                     129
#define IDR_WZD_MENU                    130
#define IDC_WZD1_TYPE                   1000
#define IDC_WZD2_TYPE                   1001
#define IDC_WZD3_TYPE                   1002
#define IDC_WZD4_TYPE                   1003
#define ID_POPUP_WZD1                   32775
#define ID_POPUP_WZD2                   32776
#define ID_POPUP_WZD3                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
