//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wzd.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WZDTYPE                     129
#define IDD_WZD_DIALOG                  130
#define IDD_WAIT_DIALOG                 131
#define IDD_DIALOG1                     132
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1001
#define ID_TEST_CREATE                  32771
#define ID_TEST_DESTROY                 32772
#define ID_TEST_WAIT                    32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
