//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Styles.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_STYLESTYPE                  129
#define IDD_BUTTONS_DIALOG              130
#define IDB_IMAGE_BITMAP                131
#define IDB_ONE_BITMAP                  132
#define IDD_DIALOG1                     133
#define IDB_COMBO_BITMAP                135
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDB_SMALL_BITMAP                140
#define IDB_LARGE_BITMAP                141
#define IDB_STATUS_BITMAP               142
#define IDD_TEST_DIALOG                 143
#define IDC_BUTTON_STYLES               32771
#define ID_STYLES_STATICS               32772
#define ID_STYLES_EDITS                 32773
#define ID_STYLES_COMBOS                32774
#define ID_STYLES_SCROOLBARS            32775
#define ID_STYLES_LISTBOXES             32776
#define ID_STYLES_EXTENDEDCOMBO         32777
#define ID_STYLES_LISTVIEW              32778
#define ID_STYLES_ANIMATION             32779
#define ID_STYLES_SLIDER                32780
#define ID_STYLES_TREEVIEW              32781
#define ID_STYLES_SPIN                  32782
#define ID_STYLES_PROGRESS              32783
#define ID_STYLES_HEADER                32784
#define ID_STYLES_TAB                   32785
#define ID_STYLES_CALENDER              32786
#define ID_STYLES_DATETIME              32787
#define ID_STYLES_PLAIN1                32788
#define ID_STYLES_PLAIN2                32789
#define ID_STYLES_DIALOG                32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
