// WzdPrjct.h : project include file
//
/////////////////////////////////////////////////////////////////////////////

#if !defined WZDPROJECT_H
#define WZDPROJECT_H

#define COMPANY_KEY "Company"
#define APPLICATION_KEY "Software\\Company\\Wzd\\Settings"
#define SETTINGS_KEY "Settings"
#define OPTION1_KEY "Option1"
#define OPTION2_KEY "Option2"
#define OPTION3_KEY "Option3"
#define OPTION4_KEY "Option4"


#endif
