//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WZD.RC
//
#define IDR_MAINFRAME				128
#define IDR_WZDTYPE				129
#define IDD_ABOUTBOX				100
#define IDS_FILE_NEW			32000
#define IDS_FILE_OPEN			32001
#define IDS_FILE_SAVE			32002
#define IDS_FILE_CUT			32003
#define IDS_FILE_COPY			32004
#define IDS_FILE_PASTE			32005
#define IDS_FILE_PRINT			32006
#define IDS_APP_ABOUT			32007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS			1
#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
