//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wzd.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_FILEOPEN                    101
#define IDR_MAINFRAME                   128
#define IDR_WZDTYPE                     129
#define IDD_WZD_DIALOG                  130
#define IDR_FILECOPY                    131
#define IDC_WZD_ANIMATE                 1000
#define IDC_STRT_BUTTON                 1001
#define IDC_STOP_BUTTON                 1002
#define ID_TEST_WZD                     32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
