#if !defined(AFX_WZDBUTTON_H__A846F4C4_ECA0_11D1_A18D_DCB3C85EBD34__INCLUDED_)
#define AFX_WZDBUTTON_H__A846F4C4_ECA0_11D1_A18D_DCB3C85EBD34__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// WzdBttn.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// CWzdButton window

class CWzdButton : public CButton
{
// Construction
public:
	CWzdButton();

// Attributes
public:

// Operations
public:

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CWzdButton)
	//}}AFX_VIRTUAL

// Implementation
public:
	virtual ~CWzdButton();

	// Generated message map functions
protected:
	//{{AFX_MSG(CWzdButton)
		// NOTE - the ClassWizard will add and remove member functions here.
	//}}AFX_MSG

	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WZDBUTTON_H__A846F4C4_ECA0_11D1_A18D_DCB3C85EBD34__INCLUDED_)
