// WzdBttn.cpp : implementation file
//

#include "stdafx.h"
#include "wzd.h"
#include "WzdBttn.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CWzdButton

CWzdButton::CWzdButton()
{
}

CWzdButton::~CWzdButton()
{
}


BEGIN_MESSAGE_MAP(CWzdButton, CButton)
	//{{AFX_MSG_MAP(CWzdButton)
		// NOTE - the ClassWizard will add and remove mapping macros here.
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CWzdButton message handlers
